# Generated by Django 4.2.5 on 2023-10-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share_service.city'),
        ),
        migrations.AddField(
            model_name='offer',
            name='available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BinaryField(null=True),
        ),
    ]
