# Generated by Django 4.2.5 on 2023-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_service', '0003_rename_available_offer_quantity_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BinaryField(null=True),
        ),
    ]
