# Generated by Django 4.2.5 on 2023-10-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_service', '0004_offer_created_at_alter_offer_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
