# Generated by Django 4.2.5 on 2023-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_service', '0006_order_total_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=3),
        ),
    ]
