# Generated by Django 4.2.5 on 2023-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_service', '0007_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In progress', max_length=20),
        ),
    ]
